import schedule
import logging
import threading
import time
import torch
import asyncio
from typing import AsyncIterator

from qwen.model import QwenForCausalLM
from qwen.cache import init_kv_cache2
from qwen.attention import build_prefill_metadata, build_decode_metadata
from qwen.sampling import Sampling
from qwen.scheduler import Scheduler, BatchRequest, ModelRequest
from qwen.constants import DEFAULT_MAX_NEW_TOKEN

logger = logging.getLogger(__name__)

def _prefill_step(model: QwenForCausalLM, batch: BatchRequest, cache):
    packed_input_ids, md = build_prefill_metadata(batch.mutable_prompt_ids, cache, model.device, model.config.cache_len)  # is_prefill=True
    hidden = model.forward(packed_input_ids, md)       # [total_tokens, H]

    # gather each seq's LAST token -> logits -> first generated token
    last_idx = md.cu_seqlens_q[1:] - 1          # [B]
    logits = model.compute_logits(hidden[last_idx])   # [B, vocab]
    next_tokens = model.sampler(logits, batch.prompt_ids, batch.output_ids, batch.sampling_meta)          # [B]

    # freeze finished rows: don't record, don't let them emit real tokens downstream
    # _prefill_step will run until finished in the non-cache scenario
    past_lens = md.cache_seqlens    # update past_lens with new cache_seqlens generated by input_ids
    batch.add_sampled_tokens(next_tokens, past_lens, model.config.eos_token_id)

def _decode_step(model: QwenForCausalLM, batch: BatchRequest, cache):
    md = build_decode_metadata(batch.past_lens, cache, model.config.cache_len)   # is_prefill=False, fresh each step
    assert batch.next_tokens is not None, "next_tokens must be set before decode step"
    hidden = model.forward(batch.next_tokens, md)  # input_ids = [B], one token per seq -> list[int]
    logits = model.compute_logits(hidden)    # [B, vocab]  (decode: every row is a last token)
    next_tokens = model.sampler(logits, batch.prompt_ids, batch.output_ids, batch.sampling_meta)      # [B]

    # freeze finished rows: don't record, don't let them emit real tokens downstream
    past_lens = md.cache_seqlens    # update past_lens by cache_seqlens( = past_lens + 1 in build_decode_metadata)
    batch.add_sampled_tokens(next_tokens, past_lens, model.config.eos_token_id, is_prefill=False)

# without scheduler, run to completion in a single thread, for benchmarking
@torch.inference_mode()
def generate(
    model: QwenForCausalLM,
    input_ids: list[list[int]],    # raw tokenizer output, list of variable-length id sequences
    max_new_tokens: int = DEFAULT_MAX_NEW_TOKEN,
    temperatures: list[float] | None = None,
    use_cache: bool = True,
) -> list[list[int]]:
    # construct BatchRequest-like state, but without the scheduler
    reqs: list[ModelRequest] = []
    for batch_idx, input_id in enumerate(input_ids):
        loop = None  # no event loop in this synchronous scenario
        sampling: Sampling | None = Sampling(temperature=temperatures[batch_idx]) if temperatures is not None else None
        reqs.append(ModelRequest(loop, input_id, sampling, max_new_tokens))

    batch_requests = BatchRequest(reqs, model.config, scheduler=None)

    _generate(model=model, batch_requests=batch_requests, use_cache=use_cache)

    # return prompt_ids + output_ids
    return [prompt_id + output_id for prompt_id, output_id in zip(batch_requests.prompt_ids, batch_requests.output_ids)]


@torch.inference_mode()
def _generate(
    model: QwenForCausalLM,
    batch_requests: BatchRequest,    # raw tokenizer output, list of variable-length id sequences
    use_cache: bool = True,
):
    if logger.isEnabledFor(logging.DEBUG):
        logger.debug(f"_generate: batch size: {len(batch_requests.reqs)}")

    new_token_budget = [
            min(request.max_new_tokens, model.config.cache_len - len(request.input_ids)) 
            for request in batch_requests.reqs
        ]
    max_cycles = min(new_token_budget)
    if logger.isEnabledFor(logging.DEBUG):
        logger.debug(f"_generate: max_cycles: {max_cycles}, cache_len: {model.config.cache_len}, new_token_budget: {new_token_budget}")
    if use_cache:
        cycles_prefill_loop, cycles_decode_loop = 1,  max_cycles- 1
        cache = init_kv_cache2(model.config, batch_requests.batch_size, model.config.cache_len)
    else:
        cycles_prefill_loop, cycles_decode_loop = max_cycles, 0
        cache = None

    # PREFILL, loop only for non-cache
    for _ in range(cycles_prefill_loop):
        previous_finished = batch_requests.finished[:]
        _prefill_step(model=model, batch=batch_requests, cache=cache)

        if all(batch_requests.finished):
            break

    # DECODE loop
    for _ in range(cycles_decode_loop):
        if all(batch_requests.finished):
            break

        _decode_step(model=model, batch=batch_requests, cache=cache)

    # finalize: if scheduler is present, notify it that this batch is done
    if batch_requests.scheduler is not None:
            batch_requests.scheduler.finish_running_batch()

class LLMEngine:
    def __init__(self, model: QwenForCausalLM, scheduler: Scheduler):
        self.model: QwenForCausalLM = model
        self.scheduler: Scheduler = scheduler          # single shared instance

    def run_to_completion(self) -> list[list[int]]:
        output_ids = []
        while self.scheduler.has_unfinished():          # closed queue → terminates
            batch_requests = self.scheduler.schedule()
            try:
                _generate(model=self.model, batch_requests=batch_requests, use_cache=True,)
                output_ids.extend(batch_requests.output_ids)       # read results directly, no Future
            except Exception as e:
                logger.exception(f"Error occurred while generating")

        return output_ids

def benchmark(engine: LLMEngine, batch_input_ids: list[list[int]],
              sampling: Sampling | None = None, max_new_tokens: int = 300) -> tuple[list[list[int]], float]:
    """Run all requests to completion without blocking, for benchmarking."""
    assert len(batch_input_ids) > 0 and len(batch_input_ids) <= engine.scheduler.max_waiting, "batch_input_ids must not be empty or longer than max_waiting queue"
    queues = []
    for input_ids in batch_input_ids:
        loop = None
        req = ModelRequest(loop, input_ids, sampling, max_new_tokens)
        if engine.scheduler.add_request(req):       # very unlikely to reject in this test scenario
            queues.append(req.token_queue)
        else:
            raise RuntimeError("Request rejected: too many waiting requests")

    t0 = time.perf_counter()
    output_ids = engine.run_to_completion()         # drains the whole queue synchronously
    elapsed = time.perf_counter() - t0

    engine.scheduler.log_stats(is_exitting=True)    # for last stats but the logging interval does not elapse.

    return output_ids, elapsed


class ServingDriver:
    def __init__(self, engine: LLMEngine):
        self._shutdown = False
        self.engine = engine
        self.lock = threading.Lock()          # lock lives HERE, not in scheduler
        self.cond = threading.Condition(self.lock)

    def start(self):
        logger.info("run_loop thread is starting")
        self._thread = threading.Thread(target=self.run_loop, daemon=True)
        self._thread.start()

    def stop(self):
        self._shutdown = True

    def submit(self, input_ids, sampling, max_new_tokens: int)  -> asyncio.Queue[int | None | Exception] | None:
        with self.cond:
            if logger.isEnabledFor(logging.DEBUG):
                logger.debug(f"submit: input_ids: {input_ids}, sampling: {sampling}")
            loop = asyncio.get_running_loop()
            req = ModelRequest(loop, input_ids, sampling, max_new_tokens)
            if self.engine.scheduler.add_request(req):
                self.cond.notify()
                return req.token_queue
            else:
                return None

    def run_loop(self):
        while not self._shutdown:
            with self.cond:
                while not self.engine.scheduler.has_unfinished() and not self._shutdown:
                    self.cond.wait()
                batch_requests = self.engine.scheduler.schedule()      # called by run_loop when idle with lock held, returns BatchRequest

            if not batch_requests:
                if logger.isEnabledFor(logging.DEBUG):
                    logger.debug("Scheduler: no work, next loop iteration")
                continue

            try:
                _generate(model=self.engine.model, batch_requests=batch_requests, use_cache=True,)
            except Exception as e:
                logger.exception(f"Error occurred while generating")
                for req in batch_requests.reqs:
                    req.loop.call_soon_threadsafe(req.token_queue.put_nowait, e) if req.loop is not None else None

async def async_generate(
    driver: ServingDriver,
    input_ids: list[int],    # one variable-length id sequence
    sampling: Sampling | None = None,
    max_new_tokens: int = DEFAULT_MAX_NEW_TOKEN,
) -> AsyncIterator[int]:
    if logger.isEnabledFor(logging.DEBUG):
        logger.debug(f"async_generate: input_ids: {input_ids}, sampling: {sampling}")
    queue = driver.submit(input_ids, sampling, max_new_tokens)
    if queue is None:
        raise RuntimeError("Request rejected: too many waiting requests")

    # output input_ids
    for tok in input_ids:
        yield tok

    # output generated tokens
    while True:
        tok = await queue.get()                # suspends coroutine, frees event loop
        if tok is None:                              # sentinel = stream end
            break
        elif isinstance(tok, Exception):
            raise tok
        else:
            yield tok



