import copy
import logging
import threading
import torch
import asyncio
from typing import AsyncIterator

from qwen.model import QwenForCausalLM
from qwen.cache import init_kv_cache2
from qwen.sampling import SamplingMetadata
from qwen.attention import build_prefill_metadata, build_decode_metadata
from qwen.request import ModelRequest
from qwen.sampling import Sampling
from qwen.scheduler import StaticScheduler

logger = logging.getLogger(__name__)

def _prefill_step(model, mutable_prompt_ids, B, cache,
                    prompt_ids, output_ids, sampling_meta, finished: list[bool], batch_max_new_tokens: list[int]):
    packed_input_ids, md = build_prefill_metadata(mutable_prompt_ids, cache, model.device, model.config.cache_len)  # is_prefill=True
    hidden = model.forward(packed_input_ids, md)       # [total_tokens, H]

    # gather each seq's LAST token -> logits -> first generated token
    last_idx = md.cu_seqlens_q[1:] - 1          # [B]
    logits = model.compute_logits(hidden[last_idx])   # [B, vocab]
    next_tokens = model.sampler(logits, prompt_ids, output_ids, sampling_meta)          # [B]

    # freeze finished rows: don't record, don't let them emit real tokens downstream
    # _prefill_step will run until finished in the non-cache scenario
    next_tokens_cpu = next_tokens.tolist()                  # single D->H, [B] ints
    for batch_idx in range(B):
        if finished[batch_idx]:
            continue
        tok = next_tokens_cpu[batch_idx]
        output_ids[batch_idx].append(tok)
        mutable_prompt_ids[batch_idx].append(tok)
        if tok in model.config.eos_token_id \
            or len(output_ids[batch_idx]) >= batch_max_new_tokens[batch_idx]:
            finished[batch_idx] = True

    past_lens = md.cache_seqlens    # update past_lens with new cache_seqlens generated by input_ids
    return past_lens, finished, next_tokens, output_ids, mutable_prompt_ids

def _decode_step(model, next_tokens, B, cache, cache_len, prompt_ids, output_ids, sampling_meta, past_lens, finished: list[bool], batch_max_new_tokens):
    md = build_decode_metadata(past_lens, cache, cache_len)   # is_prefill=False, fresh each step
    hidden = model.forward(next_tokens, md)  # input_ids = [B], one token per seq -> list[int]
    logits = model.compute_logits(hidden)    # [B, vocab]  (decode: every row is a last token)
    next_tokens = model.sampler(logits, prompt_ids, output_ids, sampling_meta)      # [B]

    # freeze finished rows: don't record, don't let them emit real tokens downstream
    next_tokens_cpu = next_tokens.tolist()                  # single D->H, [B] ints
    for batch_idx in range(B):
        if finished[batch_idx]:
            continue
        tok = next_tokens_cpu[batch_idx]
        output_ids[batch_idx].append(tok)
        if tok in model.config.eos_token_id \
            or len(output_ids[batch_idx]) >= batch_max_new_tokens[batch_idx]:
            finished[batch_idx] = True

    past_lens = md.cache_seqlens    # update past_lens by cache_seqlens( = past_lens + 1 in build_decode_metadata)
    return past_lens, finished, next_tokens, output_ids


@torch.inference_mode()
def generate(
    model: QwenForCausalLM,
    input_ids: list[list[int]],    # raw tokenizer output, list of variable-length id sequences
    max_new_tokens: int = 300,
    temperature: torch.Tensor | None = None,
    use_cache: bool = True,
) -> list[list[int]]:
    prompt_ids = input_ids
    B = len(prompt_ids)
    sampling_meta = SamplingMetadata(config=model.config, bsz=B, temperature=temperature)

    max_input_seq_length = max(len(s) for s in prompt_ids)
    max_new_tokens = min(max_new_tokens, model.config.cache_len - max_input_seq_length)
    batch_max_new_tokens = [max_new_tokens] * B
    if use_cache:
        cycles_prefill_loop, cycles_decode_loop = 1,  max_new_tokens- 1
        cache = init_kv_cache2(model.config, B, model.config.cache_len)
    else:
        cycles_prefill_loop, cycles_decode_loop = max_new_tokens, 0
        cache = None

    # persistent state, lives across the whole generation
    past_lens = torch.zeros(B, dtype=torch.int32, device=model.device)
    finished = [False] * B
    output_ids = [[] for _ in range(B)]           # collected token ids per seq

    # PREFILL, loop only for non-cache
    mutable_prompt_ids = copy.deepcopy(input_ids)
    for _ in range(cycles_prefill_loop):
        past_lens, finished, next_tokens, output_ids, mutable_prompt_ids = \
            _prefill_step(
                model=model, mutable_prompt_ids=mutable_prompt_ids, B=B, cache=cache,
                prompt_ids=prompt_ids, output_ids=output_ids,
                sampling_meta=sampling_meta, finished=finished,
                batch_max_new_tokens=batch_max_new_tokens,
            )

        if all(finished):
            break

    # DECODE loop
    for _ in range(cycles_decode_loop):
        if all(finished):
            break

        past_lens, finished, next_tokens, output_ids = \
            _decode_step(
                model=model, next_tokens=next_tokens, B=B, cache=cache, cache_len=model.config.cache_len,
                prompt_ids=prompt_ids, output_ids=output_ids,
                sampling_meta=sampling_meta, past_lens=past_lens, finished=finished,
                batch_max_new_tokens=batch_max_new_tokens,
            )

    # return prompt_ids + output_ids
    return [prompt_id + output_id for prompt_id, output_id in zip(prompt_ids, output_ids)]

@torch.inference_mode()
def _generate(
    model: QwenForCausalLM,
    batch: list[ModelRequest],    # raw tokenizer output, list of variable-length id sequences
    use_cache: bool = True,
):
    logger.info(f"_generate: batch size: {len(batch)}")
    input_ids = [req.input_ids for req in batch]
    batch_sampling = [req.sampling for req in batch]
    batch_max_new_tokens = [req.max_new_tokens for req in batch]
    sampling_meta = SamplingMetadata.from_sampling_list(batch_sampling, model.config, len(batch))
    prompt_ids = input_ids
    B = len(prompt_ids)

    new_token_budget = [min(max_new_tokens, model.config.cache_len - len(prompt_id)) for max_new_tokens, prompt_id in zip(batch_max_new_tokens, prompt_ids)]
    max_cycles = min(new_token_budget)
    if use_cache:
        cycles_prefill_loop, cycles_decode_loop = 1,  max_cycles- 1
        cache = init_kv_cache2(model.config, B, model.config.cache_len)
    else:
        cycles_prefill_loop, cycles_decode_loop = max_cycles, 0
        cache = None

    # persistent state, lives across the whole generation
    past_lens = torch.zeros(B, dtype=torch.int32, device=model.device)
    finished = [False] * B
    output_ids = [[] for _ in range(B)]           # collected token ids per seq

    # PREFILL, loop only for non-cache
    mutable_prompt_ids = copy.deepcopy(input_ids)
    for _ in range(cycles_prefill_loop):
        previous_finished = finished[:]
        past_lens, finished, next_tokens, output_ids, mutable_prompt_ids = \
            _prefill_step(
                model=model, mutable_prompt_ids=mutable_prompt_ids, B=B, cache=cache,
                prompt_ids=prompt_ids, output_ids=output_ids,
                sampling_meta=sampling_meta, finished=finished,
                batch_max_new_tokens=batch_max_new_tokens,
            )
        for idx in range(B):
            if previous_finished[idx]:
                continue
            if output_ids[idx]:
                batch[idx].loop.call_soon_threadsafe(batch[idx].token_queue.put_nowait, output_ids[idx][-1])
            if finished[idx] and output_ids[idx]:
                batch[idx].loop.call_soon_threadsafe(batch[idx].token_queue.put_nowait, None)  # sentinel = stream end

        if all(finished):
            break

    # DECODE loop
    for _ in range(cycles_decode_loop):
        if all(finished):
            break

        previous_finished = finished[:]
        past_lens, finished, next_tokens, output_ids = \
            _decode_step(
                model=model, next_tokens=next_tokens, B=B, cache=cache, cache_len=model.config.cache_len,
                prompt_ids=prompt_ids, output_ids=output_ids,
                sampling_meta=sampling_meta, past_lens=past_lens, finished=finished,
                batch_max_new_tokens=batch_max_new_tokens,
            )
        for idx in range(B):
            if previous_finished[idx]:
                continue
            if output_ids[idx]:
                batch[idx].loop.call_soon_threadsafe(batch[idx].token_queue.put_nowait, output_ids[idx][-1])
            if finished[idx] and output_ids[idx]:
                batch[idx].loop.call_soon_threadsafe(batch[idx].token_queue.put_nowait, None)  # sentinel = stream end


class LLMEngine:
    def __init__(self, model, scheduler: StaticScheduler):
        self.model = model
        self.scheduler = scheduler          # single shared instance
        self._shutdown = False

    def start(self):
        self._thread = threading.Thread(target=self.run_loop, daemon=True)
        self._thread.start()

    def submit(self, input_ids, sampling, max_new_tokens: int)  -> asyncio.Queue[int | None | Exception] | None:
        logger.info(f"submit: input_ids: {input_ids}, sampling: {sampling}")
        loop = asyncio.get_running_loop()
        req = ModelRequest(loop, input_ids, sampling, max_new_tokens)
        if self.scheduler.add_request(req):
            return req.token_queue
        else:
            return None

    # def submit_batch(self, batch_input_ids, batch_sampling, batch_max_new_tokens) -> list[asyncio.Queue[int | None] | None]:
    #     queues = []
    #     for input_ids, sampling, max_new_tokens in zip(batch_input_ids, batch_sampling, batch_max_new_tokens):
    #         loop = asyncio.get_running_loop()
    #         req = ModelRequest(loop, input_ids, sampling, max_new_tokens)
    #         if self.scheduler.add_request(req):
    #             queues.append(req.token_queue)
    #         else:
    #             queues.append(None)  # rejected due to max_waiting limit
    #     return queues

    def run_loop(self):                     # THE single execution flow
        while not self._shutdown:                # not `while True`
            batch = self.scheduler.wait_for_work()
            if not batch:
                logger.info("Scheduler: no work, next loop iteration")
                continue
            try:
                _generate(model=self.model, batch=batch, use_cache=True,)
            except Exception as e:
                logger.error(f"Error occurred while generating: {e}")
                for req in batch:
                    req.loop.call_soon_threadsafe(req.token_queue.put_nowait, e)


async def async_generate(
    engine: LLMEngine,
    input_ids: list[int],    # one variable-length id sequence
    sampling: Sampling | None = None,
    max_new_tokens: int = 300,
) -> AsyncIterator[int]:
    logger.info(f"async_generate: input_ids: {input_ids}, sampling: {sampling}")
    queue = engine.submit(input_ids, sampling, max_new_tokens)
    if queue is None:
        raise RuntimeError("Request rejected: too many waiting requests")

    # output input_ids
    for tok in input_ids:
        yield tok

    # output generated tokens
    while True:
        tok = await queue.get()                # suspends coroutine, frees event loop
        if tok is None:                              # sentinel = stream end
            break
        elif isinstance(tok, Exception):
            raise tok
        else:
            yield tok



